#!/usr/bin/env python3
"""Merge Jason (BEAM) and Elixism JSON-parse benchmark TSVs into one table.

Each input line: runtime<TAB>file<TAB>bytes<TAB>iters<TAB>us_per_parse<TAB>nodes
Joins by file basename, prints per-parse times, slowdown factor, and whether
the two parsers produced the same structural node count.
"""
import sys


def load(path):
    rows = {}
    order = []
    for line in open(path):
        p = line.rstrip("\n").split("\t")
        if len(p) != 6:
            continue
        _rt, f, byts, _iters, us, nodes = p
        base = f.split("/")[-1]
        rows[base] = (int(byts), int(us), int(nodes))
        order.append(base)
    return rows, order


jason, order = load(sys.argv[1])
elixism, _ = load(sys.argv[2])

print()
print("  JSON parsing — Jason (Elixir/BEAM)  vs  Elixism (Elixir→Wasm subset, on Guile)")
print("  " + "-" * 86)
print("  %-24s %10s %12s %14s %10s  %s"
      % ("file", "size", "Jason", "Elixism", "slowdown", "nodes"))
print("  %-24s %10s %12s %14s %10s  %s"
      % ("", "(bytes)", "(µs/parse)", "(µs/parse)", "(x)", "(match)"))
print("  " + "-" * 86)

tot_j = tot_e = 0
for base in order:
    if base not in elixism:
        continue
    jb, jus, jn = jason[base]
    eb, eus, en = elixism[base]
    tot_j += jus
    tot_e += eus
    slow = eus / jus if jus else 0
    match = "ok %d" % jn if jn == en else "DIFF %d/%d" % (jn, en)
    mark = "✓" if jn == en else "✗"
    print("  %-24s %10s %12s %14s %9.0fx  %s %s"
          % (base, f"{jb:,}", f"{jus:,}", f"{eus:,}", slow, mark, match))

print("  " + "-" * 86)
if tot_j:
    print("  %-24s %10s %12s %14s %9.0fx"
          % ("(sum of above)", "", f"{tot_j:,}", f"{tot_e:,}", tot_e / tot_j))
print()
print("  Jason's decoder is a compile-time macro-generated byte state machine on")
print("  the JIT-compiled BEAM; the Elixism parser is a recursive-descent parser")
print("  over a charlist, compiled to Guile bytecode with per-call reduction")
print("  counting. Equal node counts confirm both build the same structure.")
print()
